services:
  backend:
    image: ane21/monitoring-backend
    container_name: backend_container
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: always

  frontend:
    image: ane21/monitoring-frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always 

networks:
  app-network:
    driver: bridge